name: Ejemplo CI

on: [push] # Se ejecuta en cada push

jobs:
  build:
    runs-on: ubuntu-latest # Máquina virtual
    steps:
      - name: Descargar código
        uses: actions/checkout@v3 # Acción para clonar el repo
        
      - name: Instalar entorno
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Ejecutar pruebas
        run: |
          npm install
          npm test